spring:
  profiles:
    active: prod
  tomcat:
    max-swallow-size: 20MB
    max-http-form-post-size: 20MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 2MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  application:
    name: refund
